/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WizardRouteImport } from './routes/wizard'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as TrackRouteImport } from './routes/track'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SchemesRouteImport } from './routes/schemes'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OfficesRouteImport } from './routes/offices'
import { Route as HelplinesRouteImport } from './routes/helplines'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ComplaintsRouteImport } from './routes/complaints'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const WizardRoute = WizardRouteImport.update({
  id: '/wizard',
  path: '/wizard',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesRoute = SchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficesRoute = OfficesRouteImport.update({
  id: '/offices',
  path: '/offices',
  getParentRoute: () => rootRouteImport,
} as any)
const HelplinesRoute = HelplinesRouteImport.update({
  id: '/helplines',
  path: '/helplines',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsRoute = ComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/complaints': typeof ComplaintsRoute
  '/dashboard': typeof DashboardRoute
  '/helplines': typeof HelplinesRoute
  '/offices': typeof OfficesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schemes': typeof SchemesRoute
  '/services': typeof ServicesRoute
  '/track': typeof TrackRoute
  '/updates': typeof UpdatesRoute
  '/wizard': typeof WizardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/complaints': typeof ComplaintsRoute
  '/dashboard': typeof DashboardRoute
  '/helplines': typeof HelplinesRoute
  '/offices': typeof OfficesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schemes': typeof SchemesRoute
  '/services': typeof ServicesRoute
  '/track': typeof TrackRoute
  '/updates': typeof UpdatesRoute
  '/wizard': typeof WizardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/complaints': typeof ComplaintsRoute
  '/dashboard': typeof DashboardRoute
  '/helplines': typeof HelplinesRoute
  '/offices': typeof OfficesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schemes': typeof SchemesRoute
  '/services': typeof ServicesRoute
  '/track': typeof TrackRoute
  '/updates': typeof UpdatesRoute
  '/wizard': typeof WizardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/assistant'
    | '/auth'
    | '/complaints'
    | '/dashboard'
    | '/helplines'
    | '/offices'
    | '/reset-password'
    | '/schemes'
    | '/services'
    | '/track'
    | '/updates'
    | '/wizard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/assistant'
    | '/auth'
    | '/complaints'
    | '/dashboard'
    | '/helplines'
    | '/offices'
    | '/reset-password'
    | '/schemes'
    | '/services'
    | '/track'
    | '/updates'
    | '/wizard'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/assistant'
    | '/auth'
    | '/complaints'
    | '/dashboard'
    | '/helplines'
    | '/offices'
    | '/reset-password'
    | '/schemes'
    | '/services'
    | '/track'
    | '/updates'
    | '/wizard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  ComplaintsRoute: typeof ComplaintsRoute
  DashboardRoute: typeof DashboardRoute
  HelplinesRoute: typeof HelplinesRoute
  OfficesRoute: typeof OfficesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SchemesRoute: typeof SchemesRoute
  ServicesRoute: typeof ServicesRoute
  TrackRoute: typeof TrackRoute
  UpdatesRoute: typeof UpdatesRoute
  WizardRoute: typeof WizardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wizard': {
      id: '/wizard'
      path: '/wizard'
      fullPath: '/wizard'
      preLoaderRoute: typeof WizardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes': {
      id: '/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof SchemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offices': {
      id: '/offices'
      path: '/offices'
      fullPath: '/offices'
      preLoaderRoute: typeof OfficesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helplines': {
      id: '/helplines'
      path: '/helplines'
      fullPath: '/helplines'
      preLoaderRoute: typeof HelplinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints': {
      id: '/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof ComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  ComplaintsRoute: ComplaintsRoute,
  DashboardRoute: DashboardRoute,
  HelplinesRoute: HelplinesRoute,
  OfficesRoute: OfficesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SchemesRoute: SchemesRoute,
  ServicesRoute: ServicesRoute,
  TrackRoute: TrackRoute,
  UpdatesRoute: UpdatesRoute,
  WizardRoute: WizardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
